/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from "./routes/__root";
import { Route as AppRouteImport } from "./routes/_app/route";
import { Route as AppIndexImport } from "./routes/_app/index";
import { Route as AppAboutImport } from "./routes/_app/about";
import { Route as AppPostsIndexImport } from "./routes/_app/posts/index";
import { Route as AppPostsSplatImport } from "./routes/_app/posts/$";

// Create/Update Routes

const AppRouteRoute = AppRouteImport.update({
  id: "/_app",
  getParentRoute: () => rootRoute,
} as any);

const AppIndexRoute = AppIndexImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => AppRouteRoute,
} as any);

const AppAboutRoute = AppAboutImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => AppRouteRoute,
} as any);

const AppPostsIndexRoute = AppPostsIndexImport.update({
  id: "/posts/",
  path: "/posts/",
  getParentRoute: () => AppRouteRoute,
} as any);

const AppPostsSplatRoute = AppPostsSplatImport.update({
  id: "/posts/$",
  path: "/posts/$",
  getParentRoute: () => AppRouteRoute,
} as any);

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_app": {
      id: "/_app";
      path: "";
      fullPath: "";
      preLoaderRoute: typeof AppRouteImport;
      parentRoute: typeof rootRoute;
    };
    "/_app/about": {
      id: "/_app/about";
      path: "/about";
      fullPath: "/about";
      preLoaderRoute: typeof AppAboutImport;
      parentRoute: typeof AppRouteImport;
    };
    "/_app/": {
      id: "/_app/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof AppIndexImport;
      parentRoute: typeof AppRouteImport;
    };
    "/_app/posts/$": {
      id: "/_app/posts/$";
      path: "/posts/$";
      fullPath: "/posts/$";
      preLoaderRoute: typeof AppPostsSplatImport;
      parentRoute: typeof AppRouteImport;
    };
    "/_app/posts/": {
      id: "/_app/posts/";
      path: "/posts";
      fullPath: "/posts";
      preLoaderRoute: typeof AppPostsIndexImport;
      parentRoute: typeof AppRouteImport;
    };
  }
}

// Create and export the route tree

interface AppRouteRouteChildren {
  AppAboutRoute: typeof AppAboutRoute;
  AppIndexRoute: typeof AppIndexRoute;
  AppPostsSplatRoute: typeof AppPostsSplatRoute;
  AppPostsIndexRoute: typeof AppPostsIndexRoute;
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAboutRoute: AppAboutRoute,
  AppIndexRoute: AppIndexRoute,
  AppPostsSplatRoute: AppPostsSplatRoute,
  AppPostsIndexRoute: AppPostsIndexRoute,
};

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
);

export interface FileRoutesByFullPath {
  "": typeof AppRouteRouteWithChildren;
  "/about": typeof AppAboutRoute;
  "/": typeof AppIndexRoute;
  "/posts/$": typeof AppPostsSplatRoute;
  "/posts": typeof AppPostsIndexRoute;
}

export interface FileRoutesByTo {
  "/about": typeof AppAboutRoute;
  "/": typeof AppIndexRoute;
  "/posts/$": typeof AppPostsSplatRoute;
  "/posts": typeof AppPostsIndexRoute;
}

export interface FileRoutesById {
  __root__: typeof rootRoute;
  "/_app": typeof AppRouteRouteWithChildren;
  "/_app/about": typeof AppAboutRoute;
  "/_app/": typeof AppIndexRoute;
  "/_app/posts/$": typeof AppPostsSplatRoute;
  "/_app/posts/": typeof AppPostsIndexRoute;
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "" | "/about" | "/" | "/posts/$" | "/posts";
  fileRoutesByTo: FileRoutesByTo;
  to: "/about" | "/" | "/posts/$" | "/posts";
  id:
    | "__root__"
    | "/_app"
    | "/_app/about"
    | "/_app/"
    | "/_app/posts/$"
    | "/_app/posts/";
  fileRoutesById: FileRoutesById;
}

export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren;
}

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
};

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_app"
      ]
    },
    "/_app": {
      "filePath": "_app/route.tsx",
      "children": [
        "/_app/about",
        "/_app/",
        "/_app/posts/$",
        "/_app/posts/"
      ]
    },
    "/_app/about": {
      "filePath": "_app/about.tsx",
      "parent": "/_app"
    },
    "/_app/": {
      "filePath": "_app/index.tsx",
      "parent": "/_app"
    },
    "/_app/posts/$": {
      "filePath": "_app/posts/$.tsx",
      "parent": "/_app"
    },
    "/_app/posts/": {
      "filePath": "_app/posts/index.tsx",
      "parent": "/_app"
    }
  }
}
ROUTE_MANIFEST_END */
